### ISSUE TITLE
Magento PageBuilder causes failure during clean install

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-page-builder#730]
### Preconditions (*)
```
PHP 7.4.13 (cli) (built: Nov 24 2020 10:03:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

Magento:
```
        "magento/composer-root-update-plugin": "~1.0",
        "magento/product-enterprise-edition": "2.4.1",
```

### Steps to reproduce (*)
```
  warden env exec -- -T php-fpm bin/magento setup:install \
      --cleanup-database \
      --backend-frontname=backend \
      --amqp-host=rabbitmq \
      --amqp-port=5672 \
      --amqp-user=guest \
      --amqp-password=guest \
      --consumers-wait-for-messages=0 \
      --db-host=db \
      --db-name=magento \
      --db-user=magento \
      --db-password=magento \
      --session-save=redis \
      --session-save-redis-host=redis \
      --session-save-redis-port=6379 \
      --session-save-redis-db=2 \
      --session-save-redis-max-concurrency=20 \
      --cache-backend=redis \
      --cache-backend-redis-server=redis \
      --cache-backend-redis-db=0 \
      --cache-backend-redis-port=6379 \
      --page-cache=redis \
      --page-cache-redis-server=redis \
      --page-cache-redis-db=1 \
      --page-cache-redis-port=6379
```

### Expected result (*)
Magento installs correctly.

### Actual result (*)
```
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Eav\Api\Data\AttributeExtension::setIsPagebuilderEnabled() in /var/www/html/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php:61
Stack trace:
#0 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\PageBuilder\Plugin\Catalog\Model\Product\Attribute\RepositoryPlugin->afterGet()
#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\Product\Attribute\Repository\Interceptor->Magento\Framework\Interception\{closure}()
#2 /var/www/html/generated/code/Magento/Catalog/Model/Product/Attribute/Repository/Interceptor.php(23): Magento\Catalog\Model\Product\Attribute\Repository\Interceptor->___callPlugins()
#3 /var/www/html/vendor/magento/module-catalog-search/Setup/Patch/Data/SetInitialSearchWeightForAttributes.php(103): Magento\Catalog\Model\Product\Attribute\Repository\Interceptor->get()
#4 /var/www/html/vendor/magento/module-catalog-search/Setup/Patch/D in /var/www/html/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php on line 61
```

**Comment by guvra** [comment]
I get the same error during the command-line installation of Magento 2.4.3, with the following command:

```
bin/magento setup:install
    --admin-firstname=test
    --admin-lastname=test
    --admin-email=test@example.org
    --admin-user=admin
    --admin-password=xxxxx
    --backend-frontname=admin
    --db-host=mydb
    --db-name=test
    --db-user=test
    --db-password=xxxxx
    --base-url=https://test.local/
    --base-url-secure=https://test.local/
    --use-secure=1
    --use-secure-admin=1
    --use-rewrites=1
    --currency=EUR
    --language=en_US
    --timezone=Europe/Paris
    --cleanup-database
    --elasticsearch-host=myelasticsearch
```

I can reproduce it only when app/etc/env.php exists, but not app/etc/config.php.

So I can reproduce it with the following steps:

- Initialize a file app/etc/env.php (e.g. with cache/sessions info)
- Remove file app/etc/config (if it exists)
- Clear all cache
- Launch the setup:install command

Error:

```
[Progress: 736 / 1387]
Module 'Magento_CatalogSearch':
Enabling caches:
Current status:
layout: 1
block_html: 1
full_page: 1
Call to undefined method Magento\\Eav\\Api\\Data\\AttributeExtension::setIsPagebuilderEnabled()#0 /var/www/test/vendor/magento/framework/Interception/Interceptor.php(146): Magento\\PageBuilder\\Plugin\\Catalog\\Model\\Product\\Attribute\\RepositoryPlugin->afterGet()
#1 /var/www/test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#2 /var/www/test/generated/code/Magento/Catalog/Model/Product/Attribute/Repository/Interceptor.php(23): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->___callPlugins()
#3 /var/www/test/vendor/magento/module-catalog-search/Setup/Patch/Data/SetInitialSearchWeightForAttributes.php(103): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->get()
#4 /var/www/test/vendor/magento/module-catalog-search/Setup/Patch/Data/SetInitialSearchWeightForAttributes.php(56): Magento\\CatalogSearch\\Setup\\Patch\\Data\\SetInitialSearchWeightForAttributes->setWeight()
#5 /var/www/test/vendor/magento/framework/Setup/Patch/PatchApplier.php(162): Magento\\CatalogSearch\\Setup\\Patch\\Data\\SetInitialSearchWeightForAttributes->apply()
#6 /var/www/test/setup/src/Magento/Setup/Model/Installer.php(1094): Magento\\Framework\\Setup\\Patch\\PatchApplier->applyDataPatch()
#7 /var/www/test/setup/src/Magento/Setup/Model/Installer.php(960): Magento\\Setup\\Model\\Installer->handleDBSchemaData()
#8 [internal function]: Magento\\Setup\\Model\\Installer->installDataFixtures()
#9 /var/www/test/setup/src/Magento/Setup/Model/Installer.php(389): call_user_func_array()
#10 /var/www/test/setup/src/Magento/Setup/Console/Command/InstallCommand.php(231): Magento\\Setup\\Model\\Installer->install()
#11 /var/www/test/vendor/symfony/console/Command/Command.php(255): Magento\\Setup\\Console\\Command\\InstallCommand->execute()
#12 /var/www/test/vendor/symfony/console/Application.php(1009): Symfony\\Component\\Console\\Command\\Command->run()
#13 /var/www/test/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand()
#14 /var/www/test/vendor/magento/framework/Console/Cli.php(115): Symfony\\Component\\Console\\Application->doRun()
#15 /var/www/test/vendor/symfony/console/Application.php(149): Magento\\Framework\\Console\\Cli->doRun()
#16 /var/www/test/bin/magento(23): Symfony\\Component\\Console\\Application->run()
#17 {main}
```

**Comment by hnsr** [comment]
Also running into this with an existing M2 install that I've just upgraded from 2.4.2 to 2.4.3.

I feel this patch is more of a workaround isn't it? Shouldn't the extension attribute be available, as it seems to be properly defined in the module itself?

**Comment by enjoau** [comment]
I had the same issue after upgrading to 2.4.3.

```
Call to undefined method Magento\Eav\Api\Data\AttributeExtension::setIsPagebuilderEnabled() in 
/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php:61
```

I was following the official documentation here:
https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html


I found the `app/etc/config.php` file was missing some entries in the modules section for new modules introduced in the latest version.

Check to see if you have the following in your config file:
```
        'Magento_CatalogPageBuilderAnalytics' => 1,
        'Magento_CmsPageBuilderAnalytics' => 1,
        'Magento_PageBuilder' => 1,
        'Magento_PageBuilderAnalytics' => 1,
        'Magento_PageBuilderAdminAnalytics' => 1,
        'Magento_AwsS3PageBuilder' => 1,
```

Try adding in the above entries or do what I did below. Hopefully it solves your issue.

1. backup app/etc/config.php
2. bin/magento app:config:dump (generates a new config.php)
3. edit the file and remove everything except the modules section (up to you, we only keep the modules in this file)
4. bin/magento setup:upgrade
5. bin/magento setup:di:compile
6. bin/magento cache:clean

**Comment by hardyjohnson** [comment]
Interesting @enjoau, on a clean install I would not expect a config.php file to exist. The install command I have used (https://github.com/davidalger/warden-env-magento2/blob/develop/.warden/commands/bootstrap.cmd#L228) explicitly deletes any existing config.php file prior to the install command being run. Maybe this speaks to an undocumented dependency issue which is causing a load order problem.

**Comment by swleighton** [comment]
For anyone experiencing this issue using cloud docker, I had to updated the paths in the patch so it would run the m2-hotfixes folder using the ece-patches tool:

    diff --git a/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php     b/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php
    index c566c4d5c2a..bb7a7f8b860 100644
    --- a/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php
    +++ b/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php
    @@ -36,8 +36,9 @@
         \Magento\Catalog\Model\Product\Attribute\Repository $subject,
         \Magento\Catalog\Api\Data\ProductAttributeInterface $attribute
     ) {
    -        $isPageBuilderEnabled = $attribute->getData('extension_attributes')
    -            ? $attribute->getData('extension_attributes')->getIsPagebuilderEnabled()
    +        $extensionAttributes = $attribute->getData('extension_attributes');
    +        $isPageBuilderEnabled = $extensionAttributes && method_exists($extensionAttributes, 'getIsPagebuilderEnabled')
    +            ? $extensionAttributes->getIsPagebuilderEnabled()
             : 0;
         $attribute->setData('is_pagebuilder_enabled', $isPageBuilderEnabled);
     }
    @@ -58,7 +59,10 @@
         $extensionAttribute = $result->getExtensionAttributes()
             ? $result->getExtensionAttributes()
             : $this->extensionAttributesFactory->create();
    -        $extensionAttribute->setIsPagebuilderEnabled($isPageBuilderEnabled);
    +
    +        if (method_exists($extensionAttribute, 'setIsPagebuilderEnabled')) {
    +            $extensionAttribute->setIsPagebuilderEnabled($isPageBuilderEnabled);
    +        }
         $result->setExtensionAttributes($extensionAttribute);
         return $result;
     }

**Comment by danmooney2** [comment]
Doesn't this have the possibility to not set pagebuilder to enabled in certain places of admin on clean install?  I'm with [@hnsr](https://github.com/magento/magento2-page-builder/issues/730#issuecomment-952827678) on this issue; this fix is hacky.

**Comment by joeshelton-wagento** [comment]
Needed the following for 2.4.5
```
diff --git a/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php     b/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php
index c566c4d5c2a..bb7a7f8b860 100644
--- a/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php
+++ b/vendor/magento/module-page-builder/Plugin/Catalog/Model/Product/Attribute/RepositoryPlugin.php
@@ -36,8 +36,9 @@
         \Magento\Catalog\Model\Product\Attribute\Repository $subject,
         \Magento\Catalog\Api\Data\ProductAttributeInterface $attribute
     ) {
-        $isPageBuilderEnabled = $attribute->getData('extension_attributes')
-            ? $attribute->getData('extension_attributes')->getIsPagebuilderEnabled()
+        $extensionAttributes = $attribute->getData('extension_attributes');
+        $isPageBuilderEnabled = $extensionAttributes && method_exists($extensionAttributes, 'getIsPagebuilderEnabled')
+            ? $extensionAttributes->getIsPagebuilderEnabled()
             : 0;
         $attribute->setData('is_pagebuilder_enabled', $isPageBuilderEnabled);
     }
@@ -58,7 +59,10 @@
         $extensionAttribute = $result->getExtensionAttributes()
             ? $result->getExtensionAttributes()
             : $this->extensionAttributesFactory->create();
-        $extensionAttribute->setIsPagebuilderEnabled($isPageBuilderEnabled);
+
+        if (method_exists($extensionAttribute, 'setIsPagebuilderEnabled')) {
+            $extensionAttribute->setIsPagebuilderEnabled($isPageBuilderEnabled);
+        }
         $result->setExtensionAttributes($extensionAttribute);
         return $result;
     }
```
